name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore .\WindowsNotch.sln

      - name: Build
        run: dotnet build .\WindowsNotch.sln --configuration Release --no-restore
